import { describe, expect, it } from "vitest";

import githubActionsPlugin from "../src/plugin.js";

describe("plugin entry", () => {
    it("exports GitHub Actions plugin metadata", () => {
        expect(githubActionsPlugin.meta).toMatchObject({
            name: "eslint-plugin-github-actions-2",
            namespace: "github-actions",
        });
    });

    it("exports the expected rule names", () => {
        expect(
            Object.keys(githubActionsPlugin.rules).toSorted((left, right) =>
                left.localeCompare(right)
            )
        ).toEqual([
            "action-name-casing",
            "job-id-casing",
            "max-jobs-per-action",
            "no-case-insensitive-input-id-collision",
            "no-composite-input-env-access",
            "no-deprecated-node-runtime",
            "no-duplicate-composite-step-id",
            "no-empty-template-file-pattern",
            "no-external-job",
            "no-hardcoded-default-branch-in-template",
            "no-icon-file-extension-in-template-icon-name",
            "no-inherit-secrets",
            "no-invalid-concurrency-context",
            "no-invalid-key",
            "no-invalid-reusable-workflow-job-key",
            "no-invalid-template-file-pattern-regex",
            "no-invalid-workflow-call-output-value",
            "no-path-separators-in-template-icon-name",
            "no-post-if-without-post",
            "no-pr-head-checkout-in-pull-request-target",
            "no-pre-if-without-pre",
            "no-required-input-with-default",
            "no-secrets-in-if",
            "no-self-hosted-runner-on-fork-pr-events",
            "no-subdirectory-template-file-pattern",
            "no-template-placeholder-in-non-template-workflow",
            "no-top-level-env",
            "no-top-level-permissions",
            "no-universal-template-file-pattern",
            "no-unknown-dependabot-multi-ecosystem-group",
            "no-unknown-input-reference-in-composite",
            "no-unknown-job-output-reference",
            "no-unknown-step-reference",
            "no-untrusted-input-in-run",
            "no-unused-dependabot-enable-beta-ecosystems",
            "no-unused-input-in-composite",
            "no-write-all-permissions",
            "pin-action-shas",
            "prefer-action-yml",
            "prefer-fail-fast",
            "prefer-file-extension",
            "prefer-inputs-context",
            "prefer-step-uses-style",
            "prefer-template-yml-extension",
            "require-action-name",
            "require-action-run-name",
            "require-checkout-before-local-action",
            "require-composite-step-name",
            "require-dependabot-assignees",
            "require-dependabot-commit-message-prefix",
            "require-dependabot-directory",
            "require-dependabot-github-actions-directory-root",
            "require-dependabot-labels",
            "require-dependabot-package-ecosystem",
            "require-dependabot-patterns-for-multi-ecosystem-group",
            "require-dependabot-schedule-cronjob",
            "require-dependabot-schedule-interval",
            "require-dependabot-schedule-time",
            "require-dependabot-schedule-timezone",
            "require-dependabot-target-branch",
            "require-dependabot-updates",
            "require-dependabot-version",
            "require-job-name",
            "require-job-step-name",
            "require-job-timeout-minutes",
            "require-merge-group-trigger",
            "require-pull-request-target-branches",
            "require-run-step-shell",
            "require-template-categories",
            "require-template-file-patterns",
            "require-template-icon-file-exists",
            "require-template-icon-name",
            "require-template-workflow-name",
            "require-trigger-types",
            "require-workflow-call-input-type",
            "require-workflow-call-output-value",
            "require-workflow-concurrency",
            "require-workflow-dispatch-input-type",
            "require-workflow-interface-description",
            "require-workflow-permissions",
            "require-workflow-run-branches",
            "require-workflow-template-pair",
            "require-workflow-template-properties-pair",
            "valid-timeout-minutes",
            "valid-trigger-events",
        ]);
    });
});
